[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
comrak = "0.30.0"
console_error_panic_hook = "0.1.7"
reqwest = "0.12.9"
sauron = "0.61.9"
sauron-html-parser = "0.61.9"
